on:
  workflow_dispatch:
    inputs:
      extraParameters:
        description: "Extra Cypress parameters"
        required: false
        default: ""
        type: string
  push:
    branches:
      - master
jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      NO_COLOR: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NPM install
        run: |
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt install nodejs
          nvm npm run cypress:ci -- --browser electron
